version: '3'
services:
  mongodb:
    image: mongo
    ports:
        - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: example
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_USERNAME: root
    ports:
        - "3307:3306"
    volumes:
        - ./easyRideMysqlDb/data:/var/lib/mysql