version: '3.7'
services:
  naming-server:
    build: ./easy-ride-naming-server
    image: docker.io/sr2010sj/naming-server:latest
    ports: 
        - "8761:8761"
  api-gateway-server:
    build: ./easy-ride-api-gateway
    image: sr2010sj/api-gateway-server:latest
    ports: 
        - "8080:8080"
    depends_on:
        - naming-server
  # user-server:
  #   build: ./easy-ride-user-service
  #   ports: 
  #       - "8000:8000"
  #   depends_on:
  #       - naming-server
  #       - api-gateway-server
  # booking-server:
  #   build: ./easy-ride-booking-service
  #   image: sr2010sj/booking-server:latest
  #   ports: 
  #       - "8500:8500"
  #   depends_on:
  #       - naming-server
  #       - api-gateway-server
  webapp-server:
    build: ./easy-ride-webapp
    image: sr2010sj/webapp-server:latest
    ports: 
        - "8765:8765"
    depends_on:
        - naming-server
        - api-gateway-server